.TH "C:/xampp/htdocs/apps/WAFFLE/inc Directory Reference" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/apps/WAFFLE/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcontroller\&.php\fP"
.br
.ti -1c
.RI "file \fBfunctions\&.php\fP"
.br
.ti -1c
.RI "file \fBinit\&.php\fP"
.br
.ti -1c
.RI "file \fBjs\-array\&.php\fP"
.br
.ti -1c
.RI "file \fBpsl\-config\&.php\fP"
.br
.in -1c
