.TH "Controllers" 3 "Sun Apr 9 2017" "Version 0.35.0.0" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controllers
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Instantiates and sets new (secure) session(s) for transmitting data to/from the user's UI (or front-end) with an application's business logic (or back-end)
.PP
Manager 
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
