.TH "C:/xampp/htdocs/apps/WAFFLE/lib/.framework/error.class.php" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/apps/WAFFLE/lib/.framework/error.class.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFramework\fP"
.br
.ti -1c
.RI " \fBWAFFLE\\Framework\\IO\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
