.TH "Framework" 3 "Sun Apr 9 2017" "Version 0.35.0.0" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Framework
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Bootstrap Component Markup Assembler that parses native bootstrap component markup, containers, rows, columns, and elements\&.
.PP
Secure cryptographic encryption and decryption solutions for securing sensitive data through flat files, database cells, or other framework modules
.PP
Collection Assembly designed as an OOP wrapper to wrap around an Array of Arrays (AoA) while using lazy instantiation to create elements in this array
.PP
Error IO
.PP
[Description]
.PP
Parses files contents prior to writing, modifying, or returning contents once read from source\&.
.PP
Generates various HTML specific semantic tags that can be implemented throughout any WAFFLE web-document or application\&.
.PP
[Description]
.PP
Pre-loads special code, jobs, libraries, or style-sheets prior to an Bootstrap document (or application) rendering its body (or content)\&.
.PP
Includes various methods to establish a connection and communicate (or query) an SQL database\&.
.PP
Templating engine developed to substitute special WAFFLE tags while publishing a clean HTML document
.PP
Endorses that specific content, input, or data is appropriately organized and/or formatted prior to advancing intermediate subroutines\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
