.TH "C:/xampp/htdocs/apps/WAFFLE/inc/functions.php" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/apps/WAFFLE/inc/functions.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBControllers\fP"
.br
.ti -1c
.RI " \fBWAFFLE\\Functions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsec_session_start\fP ()"
.br
.ti -1c
.RI "\fBlogin\fP ($id, $pass, $mysqli)"
.br
.ti -1c
.RI "\fBcheckbrute\fP ($emp_id, $mysqli)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
