.TH "C:/xampp/htdocs/apps/WAFFLE/inc/init.php" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/apps/WAFFLE/inc/init.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBControllers\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$mysqli\fP = new mysqli(HOST, USER, PASSWORD, DATABASE)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$mysqli = new mysqli(HOST, USER, PASSWORD, DATABASE)"

.PP
Definition at line 13 of file init\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
