.TH "Interfaces" 3 "Tue Apr 18 2017" "Version 0.35.0.0" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interfaces
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Specifies a series of standard methods that should be implemented by default
.PP
Specifies a series of standard methods that should be implemented by default
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
