.TH "C:/xampp/htdocs/apps/WAFFLE/inc/js-array.php" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/apps/WAFFLE/inc/js-array.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$js_functions\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$js_functions"
\fBInitial value:\fP
.PP
.nf
= array(
    'modernizr'     => '<script type="text/javascript" src="/lib/modernizr/modernizr\&.dev-v2\&.8\&.3\&.js"></script>',
    'jquery'        => '<script type="text/javascript" src="/lib/jquery/jquery-1\&.12\&.3\&.min\&.js"></script>',
    'prefixfree'    => '<script type="text/javascript" src="/lib/-prefix-free/prefixfree\&.jquery\&.js"></script>',
    'dev_functions' => '<script type="text/javascript" src="/web/js/functions\&.js"></script>',
)
.fi
JavaScript Array containing the appropriate links to various js libraries & functions 
.PP
\fBAuthor:\fP
.RS 4
Justin D\&. Byrne justin@byrne-systems.com 
.RE
.PP

.PP
Definition at line 8 of file js\-array\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
