.TH "C:/xampp/htdocs/apps/WAFFLE/inc/psl-config.php" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/apps/WAFFLE/inc/psl-config.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFramework\fP"
.br
.ti -1c
.RI " \fBWAFFLE\\Framework\\Adapters\\DBA\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBHOST\fP 'localhost'"
.br
.ti -1c
.RI "const \fBUSER\fP 'bs_user'"
.br
.ti -1c
.RI "const \fBPASSWORD\fP 'd5uhup4ePUTuy5ge2ASTa6es'"
.br
.ti -1c
.RI "const \fBDATABASE\fP 'byrne_systems'"
.br
.ti -1c
.RI "const \fBSECURE\fP FALSE"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
