.TH "todo" 3 "Tue Apr 18 2017" "Version 0.35.0.0" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBGlobal \fBBootstrap::column\fP ($amount=12, $size='sm', $content, $alt=NULL)\fP" 1c
write error handling!  
.IP "\fBGlobal \fBHTML::link\fP ($href, $rel, $media=NULL, $download=false)\fP" 1c
add attributes: hreflang, media, crossorigin (5), sizes (5) and write error handling  
.IP "\fBGlobal \fBHTML::script\fP ($src, $type=false, $defer=false, $charset=false)\fP" 1c
add attributes: Integrity, Async [HTML5], and Crossorigin  
.IP "\fBGlobal \fBPreload::set_script\fP ($script)\fP" 1c
Develop file-version logic for method, so that developers can pass a simple filename in accompaniment with the version that they are attempting to set 
.PP

