.TH "WAFFLE\Framework" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAFFLE\Framework
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAdapters\fP"
.br
.ti -1c
.RI " \fBAssembly\fP"
.br
.ti -1c
.RI " \fBEncryption\fP"
.br
.ti -1c
.RI " \fBEngines\fP"
.br
.ti -1c
.RI " \fBInterfaces\fP"
.br
.ti -1c
.RI " \fBIO\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
