.TH "iTemplate" 3 "Sun Apr 9 2017" "Version 0.35.0.0" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iTemplate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBset\fP ($key, $value)"
.br
.ti -1c
.RI "\fBoutput\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBmerge\fP ($templates, $separator='\\)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for Template class
.PP
Standard interface for the Template Engine class 

.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
