.TH "WAFFLE\Framework\Adapters\DBA" 3 "Thu Jan 19 2017" "Version 0.2.3-prerelease+build" "WAFFLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAFFLE\Framework\Adapters\DBA
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBHOST\fP 'localhost'"
.br
.ti -1c
.RI "const \fBUSER\fP 'bs_user'"
.br
.ti -1c
.RI "const \fBPASSWORD\fP 'd5uhup4ePUTuy5ge2ASTa6es'"
.br
.ti -1c
.RI "const \fBDATABASE\fP 'byrne_systems'"
.br
.ti -1c
.RI "const \fBSECURE\fP FALSE"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const DATABASE 'byrne_systems'"

.PP
Definition at line 16 of file psl\-config\&.php\&.
.SS "const HOST 'localhost'"

.PP
Definition at line 13 of file psl\-config\&.php\&.
.SS "const PASSWORD 'd5uhup4ePUTuy5ge2ASTa6es'"

.PP
Definition at line 15 of file psl\-config\&.php\&.
.SS "const SECURE FALSE"

.PP
Definition at line 18 of file psl\-config\&.php\&.
.SS "const USER 'bs_user'"

.PP
Definition at line 14 of file psl\-config\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAFFLE from the source code\&.
